{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"face-recognition.ipynb","provenance":[],"mount_file_id":"1ybUhkwO4j88qjrd5tzXVbQxae2sU2ATe","authorship_tag":"ABX9TyOJo/jDk/LbdpZloqSKW7+n"},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"id":"ooszMLAWBJav","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":306},"outputId":"f86112aa-4df8-4994-8719-0c077758f2b2","executionInfo":{"status":"ok","timestamp":1587310519797,"user_tz":420,"elapsed":38857,"user":{"displayName":"akshit panwar","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjB5VUofsgmiZBho881ayuK14s6T-7-p-4m5oOecQ=s64","userId":"06141256727642723425"}}},"source":["!pip install face-recognition"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Collecting face-recognition\n","  Downloading https://files.pythonhosted.org/packages/1e/95/f6c9330f54ab07bfa032bf3715c12455a381083125d8880c43cbe76bb3d0/face_recognition-1.3.0-py2.py3-none-any.whl\n","Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from face-recognition) (1.18.2)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.6/dist-packages (from face-recognition) (7.0.0)\n","Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.6/dist-packages (from face-recognition) (7.1.1)\n","Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.6/dist-packages (from face-recognition) (19.18.0)\n","Collecting face-recognition-models>=0.3.0\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/cf/3b/4fd8c534f6c0d1b80ce0973d01331525538045084c73c153ee6df20224cf/face_recognition_models-0.3.0.tar.gz (100.1MB)\n","\u001b[K     |████████████████████████████████| 100.2MB 41kB/s \n","\u001b[?25hBuilding wheels for collected packages: face-recognition-models\n","  Building wheel for face-recognition-models (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566172 sha256=4c765494315ab6934ec6f76a9ba56881876ba356ed6486ac0a1fda018ac967e9\n","  Stored in directory: /root/.cache/pip/wheels/d2/99/18/59c6c8f01e39810415c0e63f5bede7d83dfb0ffc039865465f\n","Successfully built face-recognition-models\n","Installing collected packages: face-recognition-models, face-recognition\n","Successfully installed face-recognition-1.3.0 face-recognition-models-0.3.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"pVkyt2_cB8rV","colab_type":"code","colab":{}},"source":["import face_recognition\n","image1=face_recognition.load_image_file(\"/content/drive/My Drive/Ch06/person_1.jpg\")\n","image2=face_recognition.load_image_file(\"/content/drive/My Drive/Ch06/person_2.jpg\")\n","image3=face_recognition.load_image_file(\"/content/drive/My Drive/Ch06/person_3.jpg\")"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"nfzeMpslDA6g","colab_type":"code","colab":{}},"source":["person1=face_recognition.face_encodings(image1)\n","person2=face_recognition.face_encodings(image2)\n","person3=face_recognition.face_encodings(image3)"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"zqvVx_gADYgF","colab_type":"code","colab":{}},"source":["knownface=[person1,person2,person3]"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"1PKVnw8mFQmo","colab_type":"code","colab":{}},"source":["notknown = face_recognition.load_image_file(\"/content/drive/My Drive/Ch06/unknown_8.jpg\")\n","notknownimage = face_recognition.face_encodings(notknown)\n","for notknownimages in notknownimage:\n","  i=1\n","  if face_recognition.compare_faces(knownface,notknownimages,tolerance=0.6):\n","    print(f\"person {i} found\")\n","    i+=1\n","  else:\n","    print(\"perrson {i} not found\")\n","    i+=1"],"execution_count":0,"outputs":[]}]}